CREATE TABLE users (
  user_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR (25) UNIQUE NOT NULL,
  email VARCHAR (50) UNIQUE NOT NULL,
  full_name VARCHAR (100) NOT NULL,
  last_login TIMESTAMP,
  created_on TIMESTAMP NOT NULL
);